---
# tasks file for ansible-redis
- name: Set facts
  ansible.builtin.include_tasks: set_facts.yml

- name: Debian specific tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: RHEL specific tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: OpenSUSE specific tasks
  ansible.builtin.include_tasks: opensuse.yml
  when: ansible_os_family == "Suse"

- name: Configure Redis
  ansible.builtin.include_tasks: config.yml
  when: redis_config_redis|bool

- name: Manage Redis Services
  ansible.builtin.include_tasks: service.yml
