---
- name: Prepare hosts for testing
  hosts: all
  tasks:
    - name: Update Apt Cache
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family == "Debian"

    - name: Include ansible-bootstrap-python
      ansible.builtin.include_role:
        name: mrlesmithjr.ansible_bootstrap_python
